version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Hello from AWS CodeBuild!"
  post_build:
    commands:
      - echo "Build completed on `date`"
